### ISSUE TITLE
netxmsd aborting (double free)

### ISSUE THREAD

**Issue by martinprejsa** [netxms/netxms#124]
Versions tested: `4.5.5`, `5.0.3`
Our netxms machine has started aborting after writing this auto apply script
```
if (!$node.sysDescription ~= "RouterOS") {
	return false;
}
```
This is seems to be due to the netxmsd calling `MemFree` twice on `m_stringPtr` in `NXSL_Value::updateString`
GDB backtrace:
```
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737298404928) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737298404928) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737298404928, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff7242476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff72287f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff7289676 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff73dbb77 "%s\n")
    at ../sysdeps/posix/libc_fatal.c:155
#6  0x00007ffff72a0cfc in malloc_printerr (str=str@entry=0x7ffff73de6f0 "free(): double free detected in tcache 2")
    at ./malloc/malloc.c:5664
#7  0x00007ffff72a30ab in _int_free (av=0x7fff18000030, p=0x7fff18018040, have_lock=0) at ./malloc/malloc.c:4473
#8  0x00007ffff72a5453 in __GI___libc_free (mem=<optimized out>) at ./malloc/malloc.c:3391
#9  0x00007ffff759fe54 in MemFree (p=<optimized out>) at ../../include/nms_common.h:1075
#10 NXSL_Value::updateString (this=this@entry=0x7fff18005f78) at value.cpp:514
#11 0x00007ffff75a0675 in NXSL_Value::getValueAsString (this=this@entry=0x7fff18005f78, 
    pdwLen=pdwLen@entry=0x7ffff4ad68a4) at value.cpp:733
#12 0x00007ffff75a62c2 in NXSL_VM::matchRegexp (this=this@entry=0x7fff1801a9e0, value=value@entry=0x7fff18005f78, 
    regexp=regexp@entry=0x7fff18005340, ignoreCase=ignoreCase@entry=false) at vm.cpp:3170
#13 0x00007ffff75a9efe in NXSL_VM::doBinaryOperation (this=0x7fff1801a9e0, nOpCode=45) at vm.cpp:2503
#14 0x00007ffff75aa760 in NXSL_VM::execute (this=0x7fff1801a9e0) at vm.cpp:1637
#15 0x00007ffff75b0a40 in NXSL_VM::run (this=this@entry=0x7fff1801a9e0, args=..., globals=globals@entry=0x0, 
    expressionVariables=expressionVariables@entry=0x0, constants=constants@entry=0x0, 
    entryPoint=entryPoint@entry=0x0) at vm.cpp:429
#16 0x00007ffff7a908f5 in NXSL_VM::run (this=0x7fff1801a9e0) at ../../../include/nxsl_classes.h:1506
#17 AutoBindTarget::isApplicable (this=this@entry=0x55555f189790, 
    cachedFilterVM=cachedFilterVM@entry=0x7ffff4ad7138, 
    target=std::shared_ptr<NetObj> (use count 23, weak count 90) = {...}, dci=std::shared_ptr<DCObject> (empty) = {...}, 
    filterNumber=filterNumber@entry=0, pollContext=pollContext@entry=0x0) at abind_target.cpp:257
#18 0x00007ffff7b4314e in AutoBindTarget::isApplicable (pollContext=0x0, 
    object=std::shared_ptr<NetObj> (use count 23, weak count 90) = {...}, cachedFilterVM=0x7ffff4ad7138, 
    this=0x55555f189790) at ../../../src/server/include/nms_objects.h:1754
#19 DataCollectionTarget::applyTemplates (this=this@entry=0x55555a03f8d0) at dctarget.cpp:2243
#20 0x00007ffff7c0beb8 in Node::configurationPoll (this=0x55555a03f8d0, poller=0x7fffb00168d0, session=0x0, 
    rqId=<optimized out>) at node.cpp:4803
#21 0x00007ffff7c8540c in Pollable::doConfigurationPoll (this=0x55555a0403d0, poller=0x7fffb00168d0)
    at pollable.cpp:117
#22 0x00007ffff7c81fd0 in __ThreadPoolExecute_Wrapper_1<Pollable, PollerInfo*> (arg=0x7fffb0016b50)
    at ../../../include/nms_threads.h:1191
#23 0x00007ffff79b07a4 in ProcessSerializedRequests (data=0x7fffb0016890) at tp.cpp:499
#24 0x00007ffff79b0a03 in WorkerThread (threadInfo=0x5555557c9650) at tp.cpp:215
#25 0x00007ffff79b2b49 in ThreadCreate_Wrapper_1<WorkerThreadInfo*> (context=0x5555557c9670)
    at ../../include/nms_threads.h:539
#26 0x00007ffff7294ac3 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#27 0x00007ffff7326850 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```
This does **not** occur on fresh installs. 
This seems to be an edge case. I'll try to investigate further. Unfortunately i can't provide the core dump nor the current configuration because it contains sensitive data. Hopefully this report helps.

**Comment by 2128506** [comment]
Fixed by commit 6deba18810 in master (backported to 5.0, 4.6, and 4.5).

**Comment by 2128506** [comment]
@martinprejsa 
I have a comment on your script - it will not do what you probably want it to do. Because "not" has higher priority than "match", it will be executed first, producing false, which of course will never match pattern. Correct syntax would be
```
if (!($node.sysDescription ~= "RouterOS")) {
	return false;
}
```

**Comment by martinprejsa** [comment]
> @martinprejsa 
> I have a comment on your script - it will not do what you probably want it to do. Because "not" has higher priority than "match", it will be executed first, producing false, which of course will never match pattern. Correct syntax would be
> ```
> if (!($node.sysDescription ~= "RouterOS")) {
> 	return false;
> }
> ```
> 

I am aware of that. But the issue is that the code made it to production server and started crashing the daemon, resulting in an unusable server.
